version: "3.9"

services:
  postgres:
    image: postgres:11.1-alpine
    container_name: pg01
    hostname: 0.0.0.0
    environment:
      POSTGRES_DB: "students_db"
      POSTGRES_USER: "some_user"
      POSTGRES_PASSWORD: "some_password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U some_user -D students_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  app:
    container_name: my-warehouse-test-task
    build:
      context: .
      dockerfile: Dockerfile
    image: my-warehouse-test-task
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/students_db
      - SPRING_DATASOURCE_USERNAME=some_user
      - SPRING_DATASOURCE_PASSWORD=some_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

volumes:
  pgdata:
