version: "3.9"

services:
  postgres:
    image: postgres:11.1-alpine
    container_name: pg01
    environment:
      POSTGRES_DB: "students_db"
      POSTGRES_USER: "some_user"
      POSTGRES_PASSWORD: "some_password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U some_user -D students_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  pgdata:
